kind: ImageSetConfiguration
apiVersion: alpha1
mirror:
  operators:
  - catalog: "registry.redhat.io/redhat/redhat-operator-index:v4.13"
    packages:
    - name: aws-load-balancer-operator
      channels: 
      - name: stable-v1
      - name: alpha
