kind: ImageSetConfiguration
apiVersion: mirror.openshift/v3alpha1
mirror:
  release: 
  - version: "4.15.8"
    image: "quay.io/openshift-release-dev/ocp-release:4.15.8-x86_64"
      #$operators:
      #- catalog: "registry.redhat.io/redhat/redhat-operator-index:v4.14"
      #packages:
      #- name: aws-load-balancer-operator
      #bundles: 
      #- name: "aws-load-balancer-operator.v1.1.0"
